## Graphs

In [2]:
import numpy as np

### Definitions

#### Path
* $A \rightarrow B \iff \text{There is a path from A to B}$

#### Ancestor and Descendant
* The nodes $A$ such that $A \rightarrow B$ and $B \nrightarrow A$ are the **ancestors** of B.
* The nodes $A$ such that $A \nrightarrow B$ and $B \rightarrow A$ are the **descendants** of B.

#### DAG
* Graph $G$ is a DAG $\iff \forall A,B \in G, \big [ A \rightarrow B \iff (\text{A is an ancestor of B}) \land (\text{B is a descendant of A}) \big ]$

#### Family and Markov Blanket
* The **family** of a node is
  1. itself
  2. its parents
* The **Markov blanket** of a node is
  1. its parents
  2. its children
  3. parents of its children (**excluding itself**)
  
#### Clique
* Given an undirected graph, a **clique** is a fully connected subset of nodes. All the members of the clique are neighbors.
  * A graph is **fully connected (complete)** iff each pair of vertices is connected by an edge.
* For a maximal clique, there is no larger clique that contains the clique.

#### Singly Connected Graph (Tree)
* A graph is singly connected if there is only one path from any node $A$ to any node $B$.

### Adjacency Matrix of a Directed Graph
If the nodes are labelled in ancestral (topological) order, then the corresponding adjacency matrix is upper triangular.
  * Consider a row of the adjacency matrix. Since the nodes are labelled in topological order, all the nodes that receive an edge from the current node are listed below the current node. Hence, their indices must be greater than the current index. Then, each nonzero element in the current row must be after the diagonal entry. Since all nonzero entries on each row must come after the diagonal entry of that row, the resulting adjacency matrix must be upper-triangular. 

### Adjacency Matrix Powers
For an unweighted $N \times N$ adjacency matrix $A$, $\big[A^k_{ij}\big]$ specify how many paths there are from node $i$ to node $j$ in $k$ hops.

This is related to Markov Chains and state transitions. Assume a person is standing at each node and that if a node contains multiple outgoing edges, this person gets cloned and goes to all the target nodes. Then, start from a single node and make state transitions. $k^{th}$ state corresponds to the row of the starting node in $A^k$.

In [3]:
x = np.array([[0, 1, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 1],
              [0, 1, 0, 1]])

In [4]:
x

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 1]])

In [5]:
x@x

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 1, 1]])

In [6]:
x@x@x

array([[0, 0, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 1, 1],
       [0, 1, 1, 2]])

Persons get cloned because the column sums of the adjacency matrix were not equal to 1. If we adjust the columns to get summed to 1, then column sums of $A^k$ are always 1, for $k \in \mathbb{Z}^+$, and nobody gets cloned. They get split up, or rather, be in certain nodes with certain probabilities.

In [7]:
x = np.array([[0, 0.6, 0, 0],
              [0, 0, 1, 0],
              [1, 0, 0, 0.2],
              [0, 0.4, 0, 0.8]])

In [8]:
x

array([[ 0. ,  0.6,  0. ,  0. ],
       [ 0. ,  0. ,  1. ,  0. ],
       [ 1. ,  0. ,  0. ,  0.2],
       [ 0. ,  0.4,  0. ,  0.8]])

In [9]:
x@x

array([[ 0.  ,  0.  ,  0.6 ,  0.  ],
       [ 1.  ,  0.  ,  0.  ,  0.2 ],
       [ 0.  ,  0.68,  0.  ,  0.16],
       [ 0.  ,  0.32,  0.4 ,  0.64]])

In [10]:
x@x@x

array([[ 0.6  ,  0.   ,  0.   ,  0.12 ],
       [ 0.   ,  0.68 ,  0.   ,  0.16 ],
       [ 0.   ,  0.064,  0.68 ,  0.128],
       [ 0.4  ,  0.256,  0.32 ,  0.592]])

### Incidence Matrix
For an undirected graph with $N$ nodes and two-node cliques $C_1, \dots, C_M$, an incidence matrix is an $N \times M$ matrix in which each column $c_k$ has zeros except for ones on entries describing the $k^{th}$ two-node clique.

$C_{inc}C_{inc}^T$ is equal to the adjacency matrix except that the diagonals contain the degree of each node.